// Code generated by mockery v1.0.0. DO NOT EDIT.

package relation

import mock "github.com/stretchr/testify/mock"

// MockDialect is an autogenerated mock type for the Dialect type
type MockDialect struct {
	mock.Mock
}

// SQL provides a mock function with given fields: schema
func (_m *MockDialect) SQL(schema string) string {
	ret := _m.Called(schema)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(schema)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
