// Code generated by mockery v1.0.0. DO NOT EDIT.

package pull

import mock "github.com/stretchr/testify/mock"

// MockSQLDialect is an autogenerated mock type for the SQLDialect type
type MockSQLDialect struct {
	mock.Mock
}

// Limit provides a mock function with given fields: _a0
func (_m *MockSQLDialect) Limit(_a0 uint) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Placeholder provides a mock function with given fields: _a0
func (_m *MockSQLDialect) Placeholder(_a0 int) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
