# Copyright (C) 2021 CGI France
#
# This file is part of LINO.
#
# LINO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LINO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LINO.  If not, see <http:#www.gnu.org/licenses/>.

# Build arguments
ARG IMAGE_TAG=latest

FROM lino-venom:${IMAGE_TAG} AS venom

FROM golang:1.13 AS builder

ENV GOFLAGS="-mod=readonly"

RUN mkdir /home/lino

RUN mkdir -p /workspace
WORKDIR /workspace

ARG GOPROXY

COPY go.* /workspace/
RUN go mod download

COPY . /workspace

ARG VERSION
ARG BUILD_BY

RUN make build


FROM alpine

COPY --from=builder /workspace/bin/lino /usr/local/bin
RUN chown root:root /usr/local/bin/lino && \
    chmod +x /usr/local/bin/lino
COPY --from=venom /venom /usr/local/bin
RUN mkdir -p /home/lino/
WORKDIR /home/lino
RUN mkdir -p /tests
COPY ./tests/suites/ /tests/




