version: '3.3'

services:
   vscode:
      build: .devcontainer
      volumes:
        - ./:/workspace
        - ~/.ssh:/home/vscode/.ssh:ro
        - ~/.ssh:/root/.ssh:ro
        - ~/.git:/root/.git:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - testdata:/workspace/tests/workspace
      environment:
        - TZ=Europe/Paris
      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp:unconfined
      entrypoint: zsh -c "while sleep 1000; do :; done"
   source:
     image: frantiseks/postgres-sakila
     restart: always
     environment:
       POSTGRES_PASSWORD: sakila
     expose:
      - 5432

   dest:
     image: frantiseks/postgres-sakila
     restart: always
     environment:
       POSTGRES_PASSWORD: sakila
     expose:
     - 5432

   oracle_source:
     image: store/oracle/database-enterprise:12.2.0.1
     restart: always
     expose:
      - 1521


   lino:
    build: .
    command: http
    expose:
      - 8000
    volumes:
      - testdata:/home/lino/

   admin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: user@domain.com
        PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
        - 8080:80


volumes:
  testdata:
