# Copyright (C) 2021 CGI France
#
# This file is part of LINO.
#
# LINO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LINO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LINO.  If not, see <http:#www.gnu.org/licenses/>.

version: '3.3'

services:
   vscode:
      build:
        context: .devcontainer
        args:
          http_proxy: ${http_proxy}
          https_proxy: ${https_proxy}
          no_proxy: ${no_proxy}
      volumes:
        - ./:/workspace
        - ~/.ssh:/root/.ssh:ro
        - ~/.git:/root/.git:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - testdata:/workspace/tests/workspace
      environment:
        - TZ=Europe/Paris
        - CGO_ENABLED=1
        - PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/workspace/bin/

      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp:unconfined
      entrypoint: zsh -c "while sleep 1000; do :; done"
   source:
     image: frantiseks/postgres-sakila
     restart: always
     environment:
       POSTGRES_PASSWORD: sakila
     expose:
      - 5432

   dest:
     image: frantiseks/postgres-sakila
     restart: always
     environment:
       POSTGRES_PASSWORD: sakila
     expose:
        - 5432

   lino:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      - PASSWORD=sakila
      - CGO_ENABLED=1
      
    command: http
    expose:
      - 8000
    volumes:
      - testdata:/home/lino/

   admin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: user@domain.com
        PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
        - 8080:80


volumes:
  testdata:
