version: '3.3'

services:
   source:
     image: frantiseks/postgres-sakila
     restart: always
     environment:
       POSTGRES_PASSWORD: sakila
     ports:
      - 5432:5432
     expose:
      - 5432

   dest:
     image: frantiseks/postgres-sakila
     restart: always
     environment:
       POSTGRES_PASSWORD: sakila
     ports:
      - 5433:5432
     expose:
        - 5432

   admin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: user@domain.com
        PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
        - 80:80


   venom:
     image: lino-test:${IMAGE_TAG}
