// Code generated by mockery v1.0.0. DO NOT EDIT.

package push

import mock "github.com/stretchr/testify/mock"

// MockPlan is an autogenerated mock type for the Plan type
type MockPlan struct {
	mock.Mock
}

// FirstTable provides a mock function with given fields:
func (_m *MockPlan) FirstTable() Table {
	ret := _m.Called()

	var r0 Table
	if rf, ok := ret.Get(0).(func() Table); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Table)
		}
	}

	return r0
}

// RelationsFromTable provides a mock function with given fields: table
func (_m *MockPlan) RelationsFromTable(table Table) map[string]Relation {
	ret := _m.Called(table)

	var r0 map[string]Relation
	if rf, ok := ret.Get(0).(func(Table) map[string]Relation); ok {
		r0 = rf(table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Relation)
		}
	}

	return r0
}

// Tables provides a mock function with given fields:
func (_m *MockPlan) Tables() []Table {
	ret := _m.Called()

	var r0 []Table
	if rf, ok := ret.Get(0).(func() []Table); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Table)
		}
	}

	return r0
}
