// Code generated by mockery v1.0.0. DO NOT EDIT.

package push

import mock "github.com/stretchr/testify/mock"

// MockRowIterator is an autogenerated mock type for the RowIterator type
type MockRowIterator struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockRowIterator) Close() *Error {
	ret := _m.Called()

	var r0 *Error
	if rf, ok := ret.Get(0).(func() *Error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *MockRowIterator) Error() *Error {
	ret := _m.Called()

	var r0 *Error
	if rf, ok := ret.Get(0).(func() *Error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *MockRowIterator) Next() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Value provides a mock function with given fields:
func (_m *MockRowIterator) Value() *Row {
	ret := _m.Called()

	var r0 *Row
	if rf, ok := ret.Get(0).(func() *Row); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Row)
		}
	}

	return r0
}
