// Code generated by mockery v1.0.0. DO NOT EDIT.

package push

import mock "github.com/stretchr/testify/mock"

// MockRowWriter is an autogenerated mock type for the RowWriter type
type MockRowWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: row
func (_m *MockRowWriter) Write(row Row, translatedKeys Cache) *Error {
	ret := _m.Called(row)

	var r0 *Error
	if rf, ok := ret.Get(0).(func(Row) *Error); ok {
		r0 = rf(row)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}
