// Code generated by mockery v1.0.0. DO NOT EDIT.

package table

import mock "github.com/stretchr/testify/mock"

// MockExtractorFactory is an autogenerated mock type for the ExtractorFactory type
type MockExtractorFactory struct {
	mock.Mock
}

// New provides a mock function with given fields: url
func (_m *MockExtractorFactory) New(url string) Extractor {
	ret := _m.Called(url)

	var r0 Extractor
	if rf, ok := ret.Get(0).(func(string) Extractor); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Extractor)
		}
	}

	return r0
}
