// Code generated by mockery v1.0.0. DO NOT EDIT.

package id

import mock "github.com/stretchr/testify/mock"

// MockIngressDescriptor is an autogenerated mock type for the IngressDescriptor type
type MockIngressDescriptor struct {
	mock.Mock
}

// Relations provides a mock function with given fields:
func (_m *MockIngressDescriptor) Relations() IngressRelationList {
	ret := _m.Called()

	var r0 IngressRelationList
	if rf, ok := ret.Get(0).(func() IngressRelationList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IngressRelationList)
		}
	}

	return r0
}

// StartTable provides a mock function with given fields:
func (_m *MockIngressDescriptor) StartTable() Table {
	ret := _m.Called()

	var r0 Table
	if rf, ok := ret.Get(0).(func() Table); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Table)
		}
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *MockIngressDescriptor) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
