// Code generated by mockery v1.0.0. DO NOT EDIT.

package id

import mock "github.com/stretchr/testify/mock"

// MockPullionPlan is an autogenerated mock type for the PullionPlan type
type MockPullionPlan struct {
	mock.Mock
}

// Len provides a mock function with given fields:
func (_m *MockPullionPlan) Len() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Relations provides a mock function with given fields:
func (_m *MockPullionPlan) Relations() IngressRelationList {
	ret := _m.Called()

	var r0 IngressRelationList
	if rf, ok := ret.Get(0).(func() IngressRelationList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IngressRelationList)
		}
	}

	return r0
}

// Step provides a mock function with given fields: idx
func (_m *MockPullionPlan) Step(idx uint) Step {
	ret := _m.Called(idx)

	var r0 Step
	if rf, ok := ret.Get(0).(func(uint) Step); ok {
		r0 = rf(idx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Step)
		}
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *MockPullionPlan) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Tables provides a mock function with given fields:
func (_m *MockPullionPlan) Tables() TableList {
	ret := _m.Called()

	var r0 TableList
	if rf, ok := ret.Get(0).(func() TableList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableList)
		}
	}

	return r0
}
