// Code generated by mockery v1.0.0. DO NOT EDIT.

package id

import mock "github.com/stretchr/testify/mock"

// MockStep is an autogenerated mock type for the Step type
type MockStep struct {
	mock.Mock
}

// Cycles provides a mock function with given fields:
func (_m *MockStep) Cycles() CycleList {
	ret := _m.Called()

	var r0 CycleList
	if rf, ok := ret.Get(0).(func() CycleList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CycleList)
		}
	}

	return r0
}

// Entry provides a mock function with given fields:
func (_m *MockStep) Entry() Table {
	ret := _m.Called()

	var r0 Table
	if rf, ok := ret.Get(0).(func() Table); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Table)
		}
	}

	return r0
}

// Following provides a mock function with given fields:
func (_m *MockStep) Following() IngressRelation {
	ret := _m.Called()

	var r0 IngressRelation
	if rf, ok := ret.Get(0).(func() IngressRelation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IngressRelation)
		}
	}

	return r0
}

// Index provides a mock function with given fields:
func (_m *MockStep) Index() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// PreviousStep provides a mock function with given fields:
func (_m *MockStep) PreviousStep() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Relations provides a mock function with given fields:
func (_m *MockStep) Relations() IngressRelationList {
	ret := _m.Called()

	var r0 IngressRelationList
	if rf, ok := ret.Get(0).(func() IngressRelationList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IngressRelationList)
		}
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *MockStep) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Tables provides a mock function with given fields:
func (_m *MockStep) Tables() TableList {
	ret := _m.Called()

	var r0 TableList
	if rf, ok := ret.Get(0).(func() TableList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableList)
		}
	}

	return r0
}
