// Code generated by mockery v1.0.0. DO NOT EDIT.

package id

import mock "github.com/stretchr/testify/mock"

// MockExporter is an autogenerated mock type for the Exporter type
type MockExporter struct {
	mock.Mock
}

// Export provides a mock function with given fields: _a0
func (_m *MockExporter) Export(_a0 PullerPlan) *Error {
	ret := _m.Called(_a0)

	var r0 *Error
	if rf, ok := ret.Get(0).(func(PullerPlan) *Error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}
