// Code generated by mockery v1.0.0. DO NOT EDIT.

package dataconnector

import mock "github.com/stretchr/testify/mock"

// MockDataPingerFactory is an autogenerated mock type for the DataPingerFactory type
type MockDataPingerFactory struct {
	mock.Mock
}

// New provides a mock function with given fields: url
func (_m *MockDataPingerFactory) New(url string) DataPinger {
	ret := _m.Called(url)

	var r0 DataPinger
	if rf, ok := ret.Get(0).(func(string) DataPinger); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DataPinger)
		}
	}

	return r0
}
