// Code generated by mockery v1.0.0. DO NOT EDIT.

package dataconnector

import mock "github.com/stretchr/testify/mock"

// MockDataPinger is an autogenerated mock type for the DataPinger type
type MockDataPinger struct {
	mock.Mock
}

// Ping provides a mock function with given fields:
func (_m *MockDataPinger) Ping() *Error {
	ret := _m.Called()

	var r0 *Error
	if rf, ok := ret.Get(0).(func() *Error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}
