// Code generated by mockery v1.0.0. DO NOT EDIT.

package load

import mock "github.com/stretchr/testify/mock"

// MockRowIterator is an autogenerated mock type for the RowIterator type
type MockRowIterator struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockRowIterator) Close() *Error {
	ret := _m.Called()

	var r0 *Error
	if rf, ok := ret.Get(0).(func() *Error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}

// NextRow provides a mock function with given fields:
func (_m *MockRowIterator) NextRow() (*Row, *StopIteratorError) {
	ret := _m.Called()

	var r0 *Row
	if rf, ok := ret.Get(0).(func() *Row); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Row)
		}
	}

	var r1 *StopIteratorError
	if rf, ok := ret.Get(1).(func() *StopIteratorError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*StopIteratorError)
		}
	}

	return r0, r1
}
