// Code generated by mockery v1.0.0. DO NOT EDIT.

package load

import mock "github.com/stretchr/testify/mock"

// MockDataDestinationFactory is an autogenerated mock type for the DataDestinationFactory type
type MockDataDestinationFactory struct {
	mock.Mock
}

// New provides a mock function with given fields: url
func (_m *MockDataDestinationFactory) New(url string) DataDestination {
	ret := _m.Called(url)

	var r0 DataDestination
	if rf, ok := ret.Get(0).(func(string) DataDestination); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DataDestination)
		}
	}

	return r0
}
