// Code generated by mockery v1.0.0. DO NOT EDIT.

package load

import mock "github.com/stretchr/testify/mock"

// MockTable is an autogenerated mock type for the Table type
type MockTable struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *MockTable) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PrimaryKey provides a mock function with given fields:
func (_m *MockTable) PrimaryKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
