CREATE USER c##sakila IDENTIFIED BY sakila;
GRANT CONNECT,RESOURCE TO c##sakila;
GRANT CREATE TABLE TO c##sakila;
GRANT CREATE SESSION TO c##sakila;
GRANT UNLIMITED TABLESPACE to c##sakila;
ALTER USER c##sakila QUOTA UNLIMITED on USERS;
