// Code generated by mockery v1.0.0. DO NOT EDIT.

package relation

import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *MockStorage) List() ([]Relation, *Error) {
	ret := _m.Called()

	var r0 []Relation
	if rf, ok := ret.Get(0).(func() []Relation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Relation)
		}
	}

	var r1 *Error
	if rf, ok := ret.Get(1).(func() *Error); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*Error)
		}
	}

	return r0, r1
}

// Store provides a mock function with given fields: relations
func (_m *MockStorage) Store(relations []Relation) *Error {
	ret := _m.Called(relations)

	var r0 *Error
	if rf, ok := ret.Get(0).(func([]Relation) *Error); ok {
		r0 = rf(relations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Error)
		}
	}

	return r0
}
