// Code generated by mockery v1.0.0. DO NOT EDIT.

package extract

import mock "github.com/stretchr/testify/mock"

// MockValue is an autogenerated mock type for the Value type
type MockValue struct {
	mock.Mock
}
