// Code generated by mockery v1.0.0. DO NOT EDIT.

package extract

import mock "github.com/stretchr/testify/mock"

// MockTraceListener is an autogenerated mock type for the TraceListener type
type MockTraceListener struct {
	mock.Mock
}

// TraceStep provides a mock function with given fields: _a0, _a1
func (_m *MockTraceListener) TraceStep(_a0 Step, _a1 Filter) TraceListener {
	ret := _m.Called(_a0, _a1)

	var r0 TraceListener
	if rf, ok := ret.Get(0).(func(Step, Filter) TraceListener); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TraceListener)
		}
	}

	return r0
}
