// Code generated by mockery v1.0.0. DO NOT EDIT.

package extract

import mock "github.com/stretchr/testify/mock"

// MockFilter is an autogenerated mock type for the Filter type
type MockFilter struct {
	mock.Mock
}

// Limit provides a mock function with given fields:
func (_m *MockFilter) Limit() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Values provides a mock function with given fields:
func (_m *MockFilter) Values() Row {
	ret := _m.Called()

	var r0 Row
	if rf, ok := ret.Get(0).(func() Row); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Row)
		}
	}

	return r0
}
