// Code generated by mockery v1.0.0. DO NOT EDIT.

package extract

import mock "github.com/stretchr/testify/mock"

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: msg
func (_m *MockLogger) Debug(msg string) {
	_m.Called(msg)
}

// Error provides a mock function with given fields: msg
func (_m *MockLogger) Error(msg string) {
	_m.Called(msg)
}

// Info provides a mock function with given fields: msg
func (_m *MockLogger) Info(msg string) {
	_m.Called(msg)
}

// Trace provides a mock function with given fields: msg
func (_m *MockLogger) Trace(msg string) {
	_m.Called(msg)
}

// Warn provides a mock function with given fields: msg
func (_m *MockLogger) Warn(msg string) {
	_m.Called(msg)
}
