# This workflow republish only docker images

name: DockerHub

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Override tag with a custom value'     
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Start services
        run: docker-compose up -d vscode

      - name: Init env
        run: | 
          docker-compose exec -T -w /workspace -u root vscode usermod -u $(id -u) vscode
          docker-compose exec -T -w /workspace -u root vscode groupmod -g $(id -g) vscode
          docker-compose exec -T -w /workspace -u root vscode chown $(id -u):$(id -g) tests/workspace
          docker-compose exec -T -w /workspace -u vscode vscode touch /home/vscode/.dockerhub.yml /home/vscode/.github.yml
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker-compose exec -e GITHUB_TOKEN=${GITHUB_TOKEN} -T -u vscode vscode bash -c 'echo "GITHUB_TOKEN: ${GITHUB_TOKEN}" > ~/.github.yml'
          docker-compose exec -T -u vscode vscode bash -c 'echo "DOCKERHUB_USER: cgibot" > ~/.dockerhub.yml'
          docker-compose exec -e DOCKERHUB_PASS=${DOCKERHUB_PASS} -T -u vscode vscode bash -c 'echo "DOCKERHUB_PASS: ${DOCKERHUB_PASS}" >> ~/.dockerhub.yml'
          docker-compose exec \
            -T \
            -w /workspace \
            -u vscode \
            -e PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/vscode/go/bin:/workspace/bin \
            vscode \
            neon -props "{snapshot: true, tag: ${{ github.event.inputs.tag }}, MODULE: github.com/${CI_REPOSITORY,,}, BY: ${CI_ACTOR}, latest: true}" publish docker-push
      - name: Test version
        run: docker-compose exec -T -u vscode vscode /workspace/dist/lino_linux_amd64_v1/lino --version
